---
title: 
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\pagenumbering{gobble}

```{r include=FALSE}
source("Functions.R")
source("Constants and dependencies.R")

USA_VHA_JHU_data <- build_USA_VHA_JHU_data()
# USA_VHA_TCP_data <- build_USA_VHA_TCP_data ()
USA_VHA_JHU_clean_data = merge_census(data = USA_VHA_JHU_data, geography = "county") %>%
  group_by(State, County) %>%
  arrange(Date) %>%
  mutate(Recovered = lag(Alive , 14)) %>%
  mutate(Recovered = replace_na(Recovered, 0)) %>%
  mutate(Active = Alive - Recovered) %>%
  select(Date, State, County, VISN, Cases, Died, Active, Network, Market, Census) %>%
  group_by(State, County) %>%
  arrange(Date) %>%
  mutate(Death_rate = Died - lag(Died, lag = 1))
  


# USA_VHA_TCP_clean_data = merge_census(data = USA_VHA_TCP_data, geography = "state")

```

```{r include=FALSE}

## Filter for the states that correspond to the selected VISN ##
 VISN_states = USA_VHA_JHU_clean_data %>%
    select(State, VISN) %>%
    distinct() %>%
    filter(VISN == selected_VISN) %>%
  filter(grepl(paste(VISN_primary_states, collapse = "|"), State))

 

```

```{r}
rm(list = "county_types",
 #  "COVID_project_URL",
   "non_state",
   "packages",
   "USA_VHA_JHU_data",
   "USA_VHA_TCP_data",
   "US_cases_confirmed_URL",
   "US_cases_deceased_URL",
   "state_name_abb"
   )
```

```{r echo=FALSE}
## Format and print the TCP data table ##
table_TCP_data <- table_1 %>%
 select(current_prevalence, overall_prevalence, currently_hospitalized,
        rate_hospitalized, current_CFR, overall_CFR,
        currently_ICU, currently_vent)
kable(table_TCP_data, "latex", booktabs = TRUE, 
      col.names = c("Current", "Overall", "Current","Overall",
                    "Current", "Overall",
                     "Currently ICU", "Currently Ventilator"
                    )
      ) %>%
  kable_styling(latex_options = "striped", full_width = TRUE, font_size = 12) %>%
  footnote(number = c("Data: The COVID Project")) %>%
  column_spec(1, bold = TRUE) %>%
  add_header_above(c(" ", "Prevalence" = 2, "Hospitalized" = 2, "CFR" = 2, " " = 2)) %>%
  add_header_above(c("Current & Overall CoV-19 Community Epidemiology" = 9),
                   italic = TRUE, font_size = 14) %>%
  landscape()


```